package projeto_integrador2;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Tela_cadastro extends javax.swing.JFrame {

    public Tela_cadastro() {
        initComponents();

        ImageIcon icon = new ImageIcon(getClass().getResource("/projeto_integrador2/imagem/logo.png"));
        Image img = icon.getImage();

        Image scaledImg = img.getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), Image.SCALE_SMOOTH);
        jLabelLogo.setIcon(new ImageIcon(scaledImg));
    }
    
    Feedbacks feedbackParaAtualizar;
    public Tela_cadastro(Feedbacks feedback) {
    initComponents();
    this.feedbackParaAtualizar = feedback;

    // Preenche os campos da tela com os dados do feedback
    txaDescricao.setText(feedback.getTexto());
    checkBxAnonimato.setSelected(feedback.isAnonimo());
    
    if (feedback.getCategoria().equalsIgnoreCase("Aula")) {
        rdAula.setSelected(true);
    } else if (feedback.getCategoria().equalsIgnoreCase("Prova")) {
        rdProva.setSelected(true);
    } else if (feedback.getCategoria().equalsIgnoreCase("Matéria")) {
        rdMateria.setSelected(true);
    } else if (feedback.getCategoria().equalsIgnoreCase("Professor")) {
        rdProfessor.setSelected(true);
    } else if (feedback.getCategoria().equalsIgnoreCase("Outros")) {
        rdOutros.setSelected(true);
    }
    cbDisciplina.setSelectedItem(feedback.getDisciplina());

    // Altere o botão "Cadastrar" para "Atualizar"
    btnCadastrar.setText("Atualizar");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        label_TF = new javax.swing.JLabel();
        label_Cadastrar = new javax.swing.JLabel();
        rdAula = new javax.swing.JRadioButton();
        rdProva = new javax.swing.JRadioButton();
        rdMateria = new javax.swing.JRadioButton();
        rdProfessor = new javax.swing.JRadioButton();
        rdOutros = new javax.swing.JRadioButton();
        cbDisciplina = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        label_TF1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescricao = new javax.swing.JTextArea();
        checkBxAnonimato = new javax.swing.JCheckBox();
        botaoVoltar = new javax.swing.JButton();

        jLabel1.setText("De");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        label_TF.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        label_TF.setText("Descrição:");

        label_Cadastrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        label_Cadastrar.setText("CADASTRAR FEEDBACK");

        buttonGroup1.add(rdAula);
        rdAula.setText("Aula");
        rdAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAulaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdProva);
        rdProva.setText("Prova");

        buttonGroup1.add(rdMateria);
        rdMateria.setText("Matéria");

        buttonGroup1.add(rdProfessor);
        rdProfessor.setText("Professor");

        buttonGroup1.add(rdOutros);
        rdOutros.setText("Outros");

        cbDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discipina", " ", "Matemática", "Portugues", "História", "Geografia", "Educação Física", "Ciencias", " " }));
        cbDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDisciplinaActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 153));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        label_TF1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        label_TF1.setText("Tipo de Feedback:");

        txaDescricao.setColumns(20);
        txaDescricao.setRows(5);
        jScrollPane1.setViewportView(txaDescricao);

        checkBxAnonimato.setText("Anonimato?");

        botaoVoltar.setBackground(new java.awt.Color(0, 102, 153));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdProva)
                            .addComponent(rdMateria)
                            .addComponent(rdProfessor)
                            .addComponent(rdOutros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_TF)
                            .addComponent(cbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBxAnonimato))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdAula)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnCadastrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(label_Cadastrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(label_TF1)
                    .addContainerGap(388, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoVoltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_Cadastrar)
                .addGap(33, 33, 33)
                .addComponent(cbDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(rdAula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TF)
                    .addComponent(rdProva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkBxAnonimato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdOutros)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(label_TF1)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDisciplinaActionPerformed

    }//GEN-LAST:event_cbDisciplinaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       String texto = txaDescricao.getText();
    String disciplina = cbDisciplina.getSelectedItem().toString();

    // Determinar a categoria selecionada
    String categoria = null;
    if (rdAula.isSelected()) {
        categoria = "Aula";
    } else if (rdProva.isSelected()) {
        categoria = "Prova";
    } else if (rdMateria.isSelected()) {
        categoria = "Matéria";
    } else if (rdProfessor.isSelected()) {
        categoria = "Professor";
    } else if (rdOutros.isSelected()) {
        categoria = "Outros";
    }

    // Validação
    if (texto.isEmpty() || categoria == null || disciplina.equals("Disciplina")) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean anonimo = checkBxAnonimato.isSelected();

    FeedbacksJDBC jdbc = new FeedbacksJDBC();

    if (feedbackParaAtualizar != null) {
        // MODO DE ATUALIZAÇÃO
        feedbackParaAtualizar.setTexto(texto);
        feedbackParaAtualizar.setDisciplina(disciplina);
        feedbackParaAtualizar.setCategoria(categoria);
        feedbackParaAtualizar.setAnonimo(anonimo);

        jdbc.atualizar(feedbackParaAtualizar);
        JOptionPane.showMessageDialog(this, "Feedback atualizado com sucesso!");
    } else {
        // MODO DE CADASTRO
        Feedbacks feedback = new Feedbacks();
        feedback.setTexto(texto);
        feedback.setDisciplina(disciplina);
        feedback.setCategoria(categoria);
        feedback.setAnonimo(anonimo);

        jdbc.cadastrarFeedback(feedback);
        JOptionPane.showMessageDialog(this, "Feedback cadastrado com sucesso!");
    }

    dispose();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        Tela_principal tp = new Tela_principal();
        tp.setVisible(true);

        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void rdAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDisciplina;
    private javax.swing.JCheckBox checkBxAnonimato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Cadastrar;
    private javax.swing.JLabel label_TF;
    private javax.swing.JLabel label_TF1;
    private javax.swing.JRadioButton rdAula;
    private javax.swing.JRadioButton rdMateria;
    private javax.swing.JRadioButton rdOutros;
    private javax.swing.JRadioButton rdProfessor;
    private javax.swing.JRadioButton rdProva;
    private javax.swing.JTextArea txaDescricao;
    // End of variables declaration//GEN-END:variables
}
